---
# vars file for setup

infra__dynamic_inventory_vm_type_default:
  aws:
    sml: 'm5.large'
    std: 'm5.2xlarge'
    lrg: 'm5.4xlarge'
  azure:
    std: 'Standard_D8_v3'
    lrg: 'Standard_D16_v3'
  gcp:
    std: 'e2-standard-8'
    lrg: 'e2-standard-8'

infra__dynamic_inventory_storage_type_default:
  aws:
    std: 'gp2'
    fast: 'gp2'
  azure:
    std: 'StandardSSD_LRS'
    fast: 'StandardSSD_LRS'
  gcp:
    std: 'pd-standard'
    fast: 'pd-standard'

infra__cdp_control_plane_cidr_default:  ['52.36.110.208/32', '52.40.165.49/32', '35.166.86.177/32']

infra__dynamic_inventory_images_default:
  aws:
    el7:
      search: 'CentOS Linux 7 x86_64 HVM EBS*'
      user: 'centos'
      owners:
        - 'aws-marketplace'
    el8:
      search: 'RHEL-8.4*HVM*x86_64*'
      user: 'ec2-user'
      owners:
        - '309956199498'
    bionic:
      search: 'ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server*'
      user: 'ubuntu'
      owners:
        - '099720109477'
    focal:
      search: 'ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server*'
      user: 'ubuntu'
      owners:
        - '099720109477'

infra__all_ports_security_rule:
  aws: -1
  azure: 0-65535

infra__aws_gateway_vpc_private_endpoints: 
  - 'com.amazonaws.{{infra__region}}.s3'

infra__aws_interface_vpc_private_endpoints:
  - 'com.amazonaws.{{infra__region}}.elasticfilesystem'
  - 'com.amazonaws.{{infra__region}}.ecr.dkr'
  - 'com.amazonaws.{{infra__region}}.rds'
  - 'com.amazonaws.{{infra__region}}.ecr.api'
  - 'com.amazonaws.{{infra__region}}.sts'
  - 'com.amazonaws.{{infra__region}}.ec2'
  - 'com.amazonaws.{{infra__region}}.cloudformation'
  - 'com.amazonaws.{{infra__region}}.elasticloadbalancing'
  - 'com.amazonaws.{{infra__region}}.autoscaling'