---

# Copyright 2021 Cloudera, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# global file for common

# Role prefix is 'common__'

# Labels
common__namespace:                        "{{ globals.name_prefix | default([globals.namespace_root | default('cdp'), globals.namespace_uid | default(ansible_date_time.date | replace('-',''))] | join('-')) }}"

common__namespace_unique_suffix:          "{{ globals.labels.namespace_suffix | default(common__infra_type[:2]) }}"
common__xaccount_suffix:                  "{{ globals.labels.cross_account | default('xaccount') }}"
common__credential_suffix:                "{{ globals.labels.credential | default('cred') }}"
common__env_suffix:                       "{{ globals.labels.env | default('env') }}"
common__datalake_suffix:                  "{{ globals.labels.datalake | default('dl') }}"
common__table_suffix:                     "{{ globals.labels.table | default('table') }}"
common__vpc_name_suffix:                  "{{ globals.labels.vpc | default('net') }}"
common__vpc_subnet_suffix:                "{{ globals.labels.subnet | default('sbnt') }}"
common__vpc_svcnet_suffix:                "{{ globals.labels.service_network | default('svcnet') }}"
common__public_suffix:                    "{{ globals.labels.public | default('pub') }}"
common__private_suffix:                   "{{ globals.labels.private | default('pvt') }}"
common__security_group_knox_suffix:       "{{ globals.labels.knox | default('knox') }}"
common__security_group_default_suffix:    "{{ globals.labels.default | default('default') }}"
common__security_group_vpce_suffix:       "{{ globals.labels.vpce | default('vpce') }}"
common__role_suffix:                      "{{ globals.labels.role | default('role') }}"
common__policy_suffix:                    "{{ globals.labels.policy | default('policy') }}"
common__storage_suffix:                   "{{ globals.labels.storage | default('storage') }}"
common__identity_suffix:                  "{{ globals.labels.identity | default('identity') }}"
common__idbroker_suffix:                  "{{ globals.labels.idbroker | default('idbroker') }}"
common__logs_suffix:                      "{{ globals.labels.logs | default('logs') }}"
common__data_suffix:                      "{{ globals.labels.data | default('data') }}"
common__external_data_suffix:             "{{ globals.labels.external_data | default('external') }}"
common__datalake_admin_suffix:            "{{ globals.labels.datalake_admin | default('dladmin') }}"
common__ranger_audit_suffix:              "{{ globals.labels.ranger_audit | default('audit') }}"
common__cml_suffix:                       "{{ globals.labels.cml | default('cml') }}"
common__cde_suffix:                       "{{ globals.labels.cde | default('cde') }}"
common__igw_suffix:                       "{{ globals.labels.internet_gateway | default('igw') }}"
common__app_suffix:                       "{{ globals.labels.app | default('app') }}"
common__group_suffix:                     "{{ globals.labels.group | default('group') }}"
common__admin_suffix:                     "{{ globals.labels.admin | default('admin') }}"
common__user_suffix:                      "{{ globals.labels.user | default('user') }}"
common__ngw_suffix:                       "{{ globals.labels.nat_gateway | default('ngw') }}"

common__unique_storage_name_suffix:       "{{ globals.storage.name | default((common__region + common__aws_profile) if 'aws' in common__infra_type else common__region) }}"

# CDP Control Plane Region
common__cdp_control_plane_region:         "{{ globals.cdp_region | default('us-west-1') }}"
common__cdp_control_plane_crn:            "{{ common__cdp_control_planes[common__cdp_control_plane_region] }}"
# Infra
common__infra_deployment_engine:          "{{ globals.infra_deployment_engine | default('ansible') }}"
common__aws_profile:                      "{{ globals.aws_profile | default('') }}"
common__infra_type:                       "{{ globals.infra_type | default('aws') }}"
common__public_key_file:                  "{{ globals.ssh.public_key_file | default('') }}"
common__namespace_cdp:                    "{{ globals.namespace_cdp | default([common__namespace, common__namespace_unique_suffix] | join('-')) }}"
common__tags:                             "{{ globals.tags | default({}) }}"
common__public_key_id:                    "{{ globals.ssh.public_key_id | default('') }}"
common__public_key_text:                  "{{ globals.ssh.public_key_text | default('') }}"
common__region:                           "{{ globals.region | default(common__region_default[common__infra_type]) }}"
common__storage_name:                     "{{ infra.storage.name | default([common__namespace, common__unique_storage_name_suffix[::2] | replace('-','')] | join('-')) }}"

# Terraform
common__terraform_base_dir:               "{{ globals.terraform.base_dir | default( [playbook_dir , 'terraform'] | path_join ) }}"
# The processed Jinja template files for Terraform are placed in common__terraform_template_dir
common__terraform_template_dir:            "{{ [common__terraform_base_dir , 'processed_template_code'] | path_join }}"
# A timestamped artefact directory storing a copy of the Terraform code from each run
common__terraform_artefact_dir:            "{{ [common__terraform_base_dir , ('tf_artefacts_' + ansible_date_time.iso8601 ) ] | path_join | regex_replace(':','_')}}"
# Terraform apply/destroy run from under this directory
common__terraform_workspace_dir:           "{{ [common__terraform_base_dir, 'workspace'] | path_join }}"

common__terraform_allowed_state_storage:   "['local', 'remote_s3']"
common__terraform_state_storage:           "{{ globals.terraform.state_storage  | default('local') }}"
common__terraform_remote_state_bucket:     "{{ globals.terraform.remote_state_bucket | default('') }}"      
common__terraform_remote_state_lock_table: "{{ globals.terraform.remote_state_lock_table | default('') }}"      

common__vpc_name:                         "{{ infra.vpc.name | default([common__namespace, common__vpc_name_suffix] | join('-')) }}"
common__vpc_public_subnet_cidrs:          "{{ infra.vpc.public_subnets | default(['10.10.0.0/19', '10.10.32.0/19', '10.10.64.0/19']) }}"
common__vpc_private_subnet_cidrs:         "{{ infra.vpc.private_subnets | default(['10.10.96.0/19', '10.10.128.0/19', '10.10.160.0/19']) }}"
common__vpc_private_subnets_suffix:       "{{ infra.vpc.public_subnets_suffix | default([common__vpc_subnet_suffix, common__private_suffix] | join('-')) }}"
common__vpc_public_subnets_suffix:        "{{ infra.vpc.private_subnets_suffix | default([common__vpc_subnet_suffix, common__public_suffix] | join('-')) }}"

common__security_group_knox_name:         "{{ infra.security_group.knox.name | default([common__namespace, common__security_group_knox_name_suffix] | join('-')) }}"
common__security_group_default_name:      "{{ infra.security_group.default.name | default([common__namespace, common__security_group_default_name_suffix] | join('-')) }}"
common__security_group_vpce_name:         "{{ infra.security_group.vpce.name | default([common__namespace, common__security_group_vpce_name_suffix] | join('-')) }}"

common__security_group_knox_name_suffix:    "{{ infra.security_group.knox.suffix | default(common__security_group_knox_suffix) }}"
common__security_group_default_name_suffix: "{{ infra.security_group.default.suffix | default(common__security_group_default_suffix) }}"
common__security_group_vpce_name_suffix:    "{{ infra.security_group.vpce.suffix | default(common__security_group_vpce_suffix) }}"

common__ml_path:                          "{{ infra.storage.path.ml | default('datasci') }}"
common__de_path:                          "{{ infra.storage.path.de | default('dataeng') }}"
common__logs_path:                        "{{ infra.storage.path.logs | default(common__logs_suffix) }}"
common__data_path:                        "{{ infra.storage.path.data | default(common__data_suffix) }}"
common__ranger_audit_path:                "{{ infra.storage.path.ranger_audit | default('ranger/audit') }}"

# AWS Infra
common__aws_vpc_id:                       "{{ infra.aws.vpc.existing.vpc_id | default('') }}"
common__aws_public_subnet_ids:            "{{ infra.aws.vpc.existing.public_subnet_ids | default([]) }}"
common__aws_private_subnet_ids:           "{{ infra.aws.vpc.existing.private_subnet_ids | default([]) }}"
common__aws_region:                       "{{ infra.aws.region | default('eu-west-1') }}"
common__aws_role_suffix:                  "{{ infra.aws.role.suffix | default(common__role_suffix) }}"

common__aws_datalake_admin_role_name:     "{{ env.aws.role.name.datalake_admin | default([common__namespace, common__aws_datalake_admin_suffix, common__aws_role_suffix] | join('-')) }}"
common__aws_datalake_admin_suffix:        "{{ env.aws.role.label.datalake_admin | default(common__datalake_admin_suffix) }}"
common__aws_idbroker_role_name:           "{{ env.aws.role.name.idbroker | default([common__namespace, common__aws_idbroker_suffix, common__aws_role_suffix] | join('-')) }}"
common__aws_idbroker_suffix:              "{{ env.aws.role.label.idbroker | default(common__idbroker_suffix) }}"

# Azure Infra
common__azure_storage_name:               "{{ infra.azure.storage.name | default(common__storage_name | replace('-','')) }}"

common__azure_account_suffix:             "{{ infra.azure.netapp.account.suffix | default('account') }}"
common__azure_netapp_suffix:              "{{ infra.azure.netapp.suffix | default('netapp') }}"
common__azure_pool_suffix:                "{{ infra.azure.netapp.pool.suffix | default('pool') }}"
common__azure_volume_suffix:              "{{ infra.azure.netapp.volume.suffix | default('vol') }}"

common__azure_metagroup_name_suffix:      "{{ infra.azure.metagroup.suffix | default('rmgp') }}"
common__azure_metagroup_name:             "{{ infra.azure.metagroup.name | default([common__namespace, common__azure_metagroup_name_suffix] | join('-')) }}"
common__azure_region:                     "{{ infra.azure.region | default('westeurope') }}"
common__azure_sp_login_from_env:          "{{ infra.azure.sp_login_from_env | default(False) }}"
common__azure_netapp_account_name:        "{{ infra.azure.netapp.account.name | default([common__namespace, common__azure_netapp_suffix, common__azure_account_suffix] | join('-'))}}"
common__azure_netapp_pool_name:           "{{ infra.azure.netapp.pool.name | default([common__namespace, common__azure_netapp_suffix, common__azure_pool_suffix] | join('-')) }}"
common__azure_netapp_vol_name:            "{{ infra.azure.netapp.volume.name | default([common__namespace, common__azure_netapp_suffix, common__azure_volume_suffix] | join('-')) }}"
common__azure_netapp_nfs_version:         "{{ infra.azure.netapp.nfs.version | default('3') }}"

# GCP Infra
common__gcp_project:                      "{{ infra.gcp.project | default('gcp-se') }}"
common__gcp_region:                       "{{ infra.gcp.region | default('europe-west1') }}"
common__gcp_subnet_id:                    "{{ infra.gcp.vpc.subnet_id | default(None) }}"

# Plat
common__xaccount_credential_suffix:       "{{ env.cdp.credential.suffix | default(common__xaccount_suffix) }}"
common__xaccount_credential_name_suffix:  "{{ env.cdp.credential.name_suffix | default(common__credential_suffix) }}"
common__xaccount_credential_name:         "{{ env.cdp.credential.name | default([common__namespace_cdp, common__xaccount_credential_suffix, common__xaccount_credential_name_suffix] | join('-')) }}"

common__env_name:                         "{{ env.name | default([common__namespace_cdp, common__env_name_suffix] | join('-')) }}"
common__env_name_suffix:                  "{{ env.suffix | default(common__env_suffix) }}"

common__datalake_name:                    "{{ env.datalake.name | default([common__namespace_cdp, common__datalake_name_suffix] | join('-')) }}"
common__datalake_name_suffix:             "{{ env.datalake.suffix | default(common__datalake_suffix) }}"
common__tunnel:                           "{{ env.tunnel | default(False) }}"
common__public_endpoint_access:           "{{ env.public_endpoint_access | default(not common__tunnel) }}"
common__use_public_ip:                    "{{ env.public_endpoint_access | default(not common__tunnel) }}"

common__env_admin_password:               "{{ globals.admin_password | mandatory }}"
common__aws_policy_urls_default_root:     "https://raw.githubusercontent.com/hortonworks/cloudbreak/master/cloud-aws-common/src/main/resources/definitions/cdp"

# Deploy
common__setup_runtime:                    "{{ ml is defined or de is defined or datahub is defined or opdb is defined or dw is defined or df is defined | default(False) | bool }}"
common__setup_plat:                       "{{ env is defined or sequence__setup_runtime  | default(False) | bool }}"
common__setup_infra:                      "{{ infra is defined or sequence__setup_plat | default(False) | bool }}"
common__setup_base:                       "{{ mgmt is defined or clusters is defined | default(False) | bool }}"

common__include_ml:                        "{{ ml is defined | bool }}"
common__include_dw:                        "{{ dw is defined | bool }}"
common__include_de:                        "{{ de is defined | bool }}"
common__include_df:                        "{{ df is defined | bool }}"
common__include_datahub:                   "{{ datahub is defined | bool }}"
common__include_opdb:                      "{{ opdb is defined | bool }}"

# Teardown
common__force_teardown:                    "{{ globals.force_teardown | default(False) }}"  # WARNING: This will purge your namespace and anything related to it, use with extreme caution
