# Copyright 2025 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

argument_specs:
  main:
    short_description: "Sign of CSRs by a CA Server"
    description:
      - Generates a signed TLS certificate from a specified list of Certificate Signing Requests (CSRs).
      - The role will optionally override and backup existing certs of the same name if required.
      - Upon completion the signed certs are copied back to the Ansible controller.
    author:
      - "Jim Enright <jenright@cloudera.com>"
    options:
      csrs_to_sign:
        description: "List of full path locations of the CSRs to sign."
        type: "list"
        elements: "str"
        required: true
      copy_from_controller:
        description: "Flag to specify if the CSRs should be copied from the Ansible controller."
        type: "bool"
        default: true
      backup_old_certs:
        description:
          - Flag to specify if existing signed certs of the same name should be backed up.
        type: "bool"
        default: true
      ca_server_intermediate_path:
        description: Common base directory for all intermediate CA resources
        type: "str"
        default: "/ca/intermediate"
      ca_server_intermediate_path_certs:
        description: Path to intermediate CA certificates directory
        type: "str"
        default: "{{ ca_server_intermediate_path }}/certs"
      ca_server_intermediate_path_csr:
        description: Path to intermediate CA CSR directory
        type: "str"
        default: "{{ ca_server_intermediate_path }}/csr"
      ca_server_intermediate_key_password:
        description: Password for the intermediate CA TLS key
        type: "str"
        default: "password"
