---

# Copyright 2023 Cloudera, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

galaxy_info:
  role_name: freeipa_client
  namespace: cloudera
  author: Webster Mudge (wmudge@cloudera.com)
  description: >
    Deployment and management of Cloudera Data Platform (CDP) Public Cloud core
    services, e.g. Environments, Datalakes, Shared Data Experiences (SDX). In
    addition to the CDP services, the role handles the deployment and management
    of the cloud provider artifacts required for CDP operations, e.g. roles, policies.
  company: Cloudera
  namespace: cloudera
  license: Apache-2.0

  min_ansible_version: 2.10

  platforms:
  - name: Debian
    versions: all
  - name: Fedora
    versions: all
  - name: GenericLinux
    versions: all
  - name: MacOSX
    versions: all
  - name: Ubuntu
    versions: all

  galaxy_tags:
  - cloudera
  - cdp
  - aws
  - gcloud
  - azure