---
# Copyright 2025 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Update AWS Prefix List for extra Security Group rules
  when: infra__aws_extra_prefix_list_id is defined
  block:
    - name: Retrieve current AWS Prefix List entries
      register: __aws_extra_prefix_list_entries
      ansible.builtin.command:
        cmd: >
          aws ec2 get-managed-prefix-list-entries
          --prefix-list-id {{ infra__aws_extra_prefix_list_id }}

    - name: Set fact deltas for AWS Prefix List entries
      ansible.builtin.set_fact:
        infra__aws_extra_prefix_list_additions: "{{ infra__vpc_extra_cidr | difference(__aws_extra_prefix_list_entries_cidr) }}"
        infra__aws_extra_prefix_list_deletions: "{{ __aws_extra_prefix_list_entries_cidr | difference(infra__vpc_extra_cidr) }}"
      vars:
        __aws_extra_prefix_list_entries_cidr: "{{ (__aws_extra_prefix_list_entries.stdout | from_json)['Entries'] | map(attribute='Cidr') | list }}"

    - name: Remove entries from AWS Prefix List
      when: infra__aws_extra_prefix_list_deletions
      ansible.builtin.command:
        cmd: >
          aws ec2 modify-managed-prefix-list
          --prefix-list-id {{ infra__aws_extra_prefix_list_id }}
          --remove-entries {{ ['Cidr='] | product(infra__aws_extra_prefix_list_deletions) | map('join') | join(' ') }}

    - name: Update AWS Prefix List maximum length
      when: infra__aws_extra_prefix_list_additions or infra__aws_extra_prefix_list_deletions
      ansible.builtin.command:
        cmd: aws ec2 modify-managed-prefix-list --prefix-list-id {{ infra__aws_extra_prefix_list_id }} --max-entries {{ infra__vpc_extra_cidr | count }}

    - name: Add entries to AWS Prefix List
      when: infra__aws_extra_prefix_list_additions
      ansible.builtin.command:
        cmd: >
          aws ec2 modify-managed-prefix-list
          --prefix-list-id {{ infra__aws_extra_prefix_list_id }}
          --add-entries {{ ['Cidr='] | product(infra__aws_extra_prefix_list_additions) | map('join') | product([',Description=']) | map('join') | join(' ') }}

- name: Create AWS Prefix List for extra Security Group rules
  when: infra__aws_extra_prefix_list_id is undefined
  block:
    - name: Create AWS Prefix List with extra CIDR entries
      register: __aws_extra_prefix_creation
      ansible.builtin.command:
        cmd: >
          aws ec2 create-managed-prefix-list
          --prefix-list-name {{ infra__aws_extra_prefix_list_name }}
          --address-family IPv4
          --max-entries {{ infra__vpc_extra_cidr | count }}
          --entries {{ ['Cidr='] | product(infra__vpc_extra_cidr) | map('join') | product([',Description=']) | map('join') | join(' ') }}

    - name: Set fact AWS Prefix List for extra entries
      ansible.builtin.set_fact:
        infra__aws_extra_prefix_list_id: "{{ (__aws_extra_prefix_creation.stdout | from_json)['PrefixList']['PrefixListId'] }}"

- name: Update AWS Prefix List tags
  when: infra__aws_extra_prefix_list_tags is defined
  ansible.builtin.command:
    cmd: >
      aws ec2 create-tags
      --resources {{ infra__aws_extra_prefix_list_id }}
      --tag {{ infra__aws_extra_prefix_list_tags | join(' ') }}
