---
# Copyright 2023 Cloudera, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Remove AWS Buckets
  when: infra__teardown_deletes_data
  amazon.aws.s3_bucket:
    region: "{{ infra__region }}"
    name: "{{ __aws_storage_location_item.bucket }}"
    state: absent
    force: true
  loop_control:
    loop_var: __aws_storage_location_item
  loop: "{{ infra__aws_storage_locations }}"

- name: Remove AWS Storage Utility Bucket
  when: infra__teardown_auto_repo_mirror | bool
  amazon.aws.s3_bucket:
    region: "{{ infra__region }}"
    name: "{{ infra__utlity_bucket_name }}"
    state: absent
    force: true

- name: Remove AWS EFS File Systems, if Discovered during Purge
  when:
    - infra__force_teardown | bool
    - __infra_efs_fs is defined and __infra_efs_fs.results is defined
    - __infra_efs_fs.results | community.general.json_query('[*].efs') | flatten | length > 0
  community.aws.efs:
    state: absent
    id: "{{ __infra_efs_item.file_system_id }}"
    wait: true
  loop: "{{ __infra_efs_fs.results | community.general.json_query('[*].efs') | flatten }}"
  loop_control:
    loop_var: __infra_efs_item
    label: "{{ __infra_efs_item.file_system_id }}"

- name: Remove Orphaned EBS Volumes during Purge
  when:
    - infra__force_teardown | bool
    - __infra_aws_ebs_vols is defined
    - __infra_aws_ebs_vols.volumes | length > 0
    - __infra_aws_ebs_item.attachment_set | length < 1
  amazon.aws.ec2_vol:
    id: "{{ __infra_aws_ebs_item.id }}"
    state: absent
  loop: "{{ __infra_aws_ebs_vols.volumes }}"
  loop_control:
    loop_var: __infra_aws_ebs_item
    label: "{{ __infra_aws_ebs_item.id }}"
