# Copyright 2024 Cloudera, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install PostgreSQL common repository
  ansible.builtin.yum_repository:
    name: pgdg-common
    description: PostgreSQL common for RHEL/CentOS
    baseurl: "https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-$releasever-$basearch"
    gpgkey: "https://download.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-{{ (ansible_architecture == 'arm64') | ternary('AARCH64-', '') }}RHEL"
  when: not skip_rdbms_repo_setup

- name: Install PostgreSQL version repository
  ansible.builtin.yum_repository:
    name: pgdg
    description: PostgreSQL {{ postgresql_version }} for RHEL/CentOS
    baseurl: "https://download.postgresql.org/pub/repos/yum/{{ postgresql_version }}/redhat/rhel-$releasever-$basearch"
    gpgkey: "https://download.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-{{ (ansible_architecture == 'arm64') | ternary('AARCH64-', '') }}RHEL"
  when: not skip_rdbms_repo_setup

- name: Disable default Postgres module in RHEL 8 or greater
  ansible.builtin.command: dnf module disable -qy postgresql
  register: __postgres_module_result
  changed_when:
    - '"Disabling modules" in __postgres_module_result.stdout'
  failed_when:
    - __postgres_module_result.rc != 0 and __postgres_module_result.rc != 1
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int >= 8

- name: Install PostgreSQL
  ansible.builtin.include_role:
    name: geerlingguy.postgresql

- name: Fix UTF-8 template
  ansible.builtin.include_tasks:
    file: postgresql/template_fix.yml

- name: Remove repositories and clean metadata
  ansible.builtin.yum_repository:
    name: "{{ repo }}"
    state: absent
  loop:
    - pgdg-common
    - pgdg
  loop_control:
    loop_var: repo
  when: not skip_rdbms_repo_setup
  notify: yum clean metadata

- name: Install psycopg2 build prerequisites
  when: ansible_distribution_major_version == "8"
  ansible.builtin.package:
    name:
      - gcc
      - libpq-devel

# This fails if the PSQL repositories are not removed
- name: Install psycopg2 library
  ansible.builtin.pip:
    name: psycopg2-binary
