---
# Copyright 2023 Cloudera, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Sequential management (individual tasks that execute implicit runlevel dependencies and order-of-operations)

- name: Deprecation warning
  run_once: true
  cloudera.exe.deprecation:
    msg: "Role, {{ ansible_role_name }}, is no longer supported."
    version: 4.0.0

- name: Validate Infrastructure Configuration
  ansible.builtin.include_role:
    name: cloudera.exe.infrastructure
    tasks_from: validate
    apply:
      tags:
        - validate
        - infra
        - plat
        - run
        - ml
        - dw
        - opdb
        - dh
  tags:
    - validate
    - infra
    - plat
    - run
    - ml
    - dw
    - opdb
    - dh

- name: Validate Platform Configuration
  ansible.builtin.include_role:
    name: cloudera.exe.platform
    tasks_from: validate
    apply:
      tags:
        - validate
        - plat
        - run
        - ml
        - dw
        - opdb
        - dh
  tags:
    - validate
    - plat
    - run
    - ml
    - dw
    - opdb
    - dh

- name: Validate Runtime Configuration
  ansible.builtin.include_role:
    name: cloudera.exe.runtime
    tasks_from: validate
    apply:
      tags:
        - validate
        - run
        - ml
        - dw
        - opdb
        - dh
  tags:
    - validate
    - run
    - ml
    - dw
    - opdb
    - dh

- name: Initialize Runtime Teardown
  ansible.builtin.include_role:
    name: cloudera.exe.runtime
    tasks_from: initialize_teardown
    apply:
      tags:
        - teardown
        - infra
        - plat
  tags:
    - teardown
    - infra
    - plat
    - never

- name: Teardown Runtime
  ansible.builtin.include_role:
    name: cloudera.exe.runtime
    tasks_from: teardown
    apply:
      tags:
        - teardown
        - infra
        - plat
  tags:
    - teardown
    - infra
    - plat
    - never

- name: Initialize Platform Teardown
  ansible.builtin.include_role:
    name: cloudera.exe.platform
    tasks_from: initialize_teardown
    apply:
      tags:
        - teardown
        - infra
  tags:
    - teardown
    - infra
    - never

- name: Teardown Platform
  ansible.builtin.include_role:
    name: cloudera.exe.platform
    tasks_from: teardown
    apply:
      tags:
        - teardown
        - infra
  tags:
    - teardown
    - infra
    - never

- name: Initialize Infrastructure Teardown
  ansible.builtin.include_role:
    name: cloudera.exe.infrastructure
    tasks_from: initialize_teardown
    apply:
      tags:
        - teardown
  tags:
    - teardown
    - never

- name: Teardown Infrastructure
  ansible.builtin.include_role:
    name: cloudera.exe.infrastructure
    tasks_from: teardown
    apply:
      tags:
        - teardown
  tags:
    - teardown
    - never

- name: Initialize Infrastructure Setup
  when: sequence__setup_infra | bool
  ansible.builtin.include_role:
    name: cloudera.exe.infrastructure
    tasks_from: initialize_setup
    apply:
      tags:
        - init
        - infra
        - plat
        - run
        - ml
        - dw
        - opdb
        - dh
  tags:
    - init
    - infra
    - plat
    - run
    - ml
    - dw
    - opdb
    - dh

- name: Setup Infrastructure
  when: sequence__setup_infra | bool
  ansible.builtin.include_role:
    name: cloudera.exe.infrastructure
    tasks_from: setup
    apply:
      tags:
        - infra
        - plat
        - run
        - ml
        - dw
        - opdb
        - dh
  tags:
    - infra
    - plat
    - run
    - ml
    - dw
    - opdb
    - dh

- name: Initialize Platform Setup
  when: sequence__setup_plat | bool
  ansible.builtin.include_role:
    name: cloudera.exe.platform
    tasks_from: initialize_setup
    apply:
      tags:
        - init
        - plat
        - run
        - ml
        - dw
        - opdb
        - dh
  tags:
    - init
    - plat
    - run
    - ml
    - dw
    - opdb
    - dh

- name: Setup Platform
  when: sequence__setup_plat | bool
  ansible.builtin.include_role:
    name: cloudera.exe.platform
    tasks_from: setup
    apply:
      tags:
        - plat
        - run
        - ml
        - dw
        - opdb
        - dh
  tags:
    - plat
    - run
    - ml
    - dw
    - opdb
    - dh

- name: Initialize Runtime Setup
  when: sequence__setup_runtime | bool
  ansible.builtin.include_role:
    name: cloudera.exe.runtime
    tasks_from: initialize_setup
    apply:
      tags:
        - init
        - run
        - ml
        - dw
        - opdb
        - dh
  tags:
    - init
    - run
    - ml
    - dw
    - opdb
    - dh

- name: Setup Runtime
  when: sequence__setup_runtime | bool
  ansible.builtin.include_role:
    name: cloudera.exe.runtime
    tasks_from: setup
    apply:
      tags:
        - run
  tags:
    - run
    - ml
    - dw
    - opdb
    - dh
