---
postgresql_global_config_options:
  - option: log_directory
    value: 'log'
  - option: listen_addresses
    value: '*'
  - option: max_connections
    value: 300
  - option: ssl
    value: "{{ 'on' if database_tls else 'off' }}"
  - option: ssl_cert_file
    value: "{{ tls_cert_path_generic if database_tls else None }}"
  - option: ssl_key_file
    value: "{{ tls_key_path_plaintext_generic if database_tls else None }}"
  - option: ssl_ca_file
    value: "{{ tls_chain_path if database_tls else None }}"

postgresql_hba_entries:
  - {type: local, database: all, user: postgres, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: peer}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: md5}
  - {type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5}
