# Copyright 2025 Cloudera, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

argument_specs:
  main:
    short_description: "Generates a CSR on each host and copies it back to the Ansible controller"
    description:
      - Generates a TLS Certificate Signing Request (CSR).
      - Once created the CSR file is copied back to the Ansibles controller.
    author:
      - "Jim Enright <jenright@cloudera.com>"
    version_added: "3.0.0"
    options:
      base_dir_security:
        description: "Base directory for Cloudera CDP security related files"
        type: "str"
        default: "/opt/cloudera/security"
      base_dir_security_pki:
        description: "Base directory for Cloudera CDP PKI security related files"
        type: "str"
        default: "{{ base_dir_security }}/pki"
      tls_csr_path:
        description: "Location of the OpenSSL Certificate Signing Request file that will be created by the role"
        type: "str"
        default: "{{ base_dir_security_pki }}/{{ inventory_hostname }}.csr"
      ca_server_attrs_general:
        description: "Attributes to use in the certificate signing request"
        type: "dict"
        default:
          OU: PS
          O: "Cloudera, Inc."
          ST: "CA"
          C: "US"
      tls_key_password:
        description: "Password for the TLS Key."
        type: "str"
        default: "changeme"
      tls_key_path:
        description: "Location of the TLS key."
        type: "str"
        default: "{{ base_dir_security_pki }}/{{ inventory_hostname }}.key"
      local_csrs_dir:
        description: "Location on the Ansible Controller where the CSR will be copied."
        type: "str"
        default: "{{ base_dir_security_pki }}/{{ inventory_hostname }}.key"
