---
mysql_repo_key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

mysql_root_password: 'Super$ecret1'
mysql_user_password: 'Super$ecret1'
mysql_daemon: mysqld
mysql_log_error: /var/log/mysqld.log
mysql_syslog_tag: mysqld
mysql_pid_file: /var/run/mysqld/mysqld.pid
mysql_socket: /var/lib/mysql/mysql.sock
mysql_config_include_files:
  - src: "cloudera.cnf"
    force: true
